services:
  blog:
    image: ${BLOG_IMAGE:-ghcr.io/tursom/turblog}:${BLOG_VERSION:-latest}
    restart: unless-stopped
    expose:
      - '8080'
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
